---
collections:
  - name: community.general
    version: 5.8.6
  - name: community.sops
    version: 1.6.4
  - name: ansible.posix
    version: 1.5.4
roles:
  - src: xanmanning.k3s
    version: v3.3.1
