---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    age: >-
      age15z2406qz970ed0p8ptd30pu5k9cl7ph6x6fvjvpaxvqc4pslnfms68ftet
  - path_regex: cluster/.*\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    age: >-
      age15z2406qz970ed0p8ptd30pu5k9cl7ph6x6fvjvpaxvqc4pslnfms68ftet
