apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: ceph-bucket
  #namespace: rook-ceph 
spec:
  
  generateBucketName: thanos-bucket
  storageClassName: rook-ceph-bucket
  # additionalConfig: [5]
  #   maxObjects: "1000"
  #   maxSize: "2G"
