# yamllint disable
# objstore.yml: |-
#     type: s3
#     config:
#       bucket:
#       endpoint:
#       access_key:
#       secret_key:
#       insecure: true
apiVersion: v1
kind: Secret
metadata:
    name: thanos-objstore
    namespace: monitoring
stringData:
    objstore.yml: ENC[AES256_GCM,data:/uvrYpENE6yhBlAOwVdZVHupPDSIkTW6eVbhgiAjZH2+T6Etlfxsdqf28QsFwecgG1/PMS0Kuu+KNX/SMLnZ/qaL8PMonzxQ+gSw1YyYiUao6q3XXVDS6qzUCX1IymQFLrZIxeWwf16fqmVCNq3upiAYbGYaIsFG5pmPOoi7aPypEHdQ8LsZe+osmOZZgvAcxDGWXO0hQ0c+gfzKfw5QxLHv+r+LWyMqDg==,iv:FfwT+hrH2CtZQ6baXo+XE+5+zqmzDTSu9+MEhK5D0zY=,tag:ZF8x6BbRd1DkVUKcD/l6aA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15uzrw396e67z9wdzsxzdk7ka0g2gr3l460e0slaea563zll3hdfqwqxdta
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwcUw0Wnk2ZGZkaTdseENp
            eHF2Vi8zUFlQSThNOVU0UkF3QlVkR2ZvU1d3CkdGOVA5Qmp1aUFSdUEyQWk5aCsy
            WmxNQVZSUkZScnlSamo5eWNtVHhBaUkKLS0tIDNuV2tvTmVtTHowLyszQlBaYnBN
            SVh4Y3J5WGFzb3hpQzdybVFzR0s5K1EKJtIOAjeHXlM11E5gJIyILsMPdbagTh2l
            IPAIDEA9PCDkdtnsk1+m7JPUOkk9uu8tFmbZ13KWYcK0ZpjPsHug8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-10T23:38:19Z"
    mac: ENC[AES256_GCM,data:mFjkCu5eHFNu5pwxSkSI804AE9rWeL4/YyAPbMpdEE8oN18lcc2uwJ6xDLk+IWLD2YCNZjUvapip1DJN+51YtMF/FRPGzpIvCJAfjjGdvHpc1xvZ04xvJVLlwVNA+bWkjRNbMxAdhp0WR2IYNLEWrO2z9A/FRdGtWL3VktuXtOs=,iv:GwXvRT/CzpuZf/JdN6Zk7DagWNJQ5ztK/tMoh5MYPm8=,tag:hebThpl42/tnq1VLXIE9rg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
