---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: benji-charts
  namespace: flux-system
spec:
  interval: 15m
  url: https://github.com/elemental-lf/benji/tree/master/charts
  timeout: 3m
