---
kubernetes:
  children:
    master:
      hosts:
       
          # rook_partitions:
          #   - /dev/sda3
        #  kubevip_interface: eth0
        k3s-fsc-1:
          ansible_host: 192.168.1.5
          ansible_user: kubeadm
        #  kubevip_interface: enp0s25
        k3s-fsc-2:
          ansible_host: 192.168.1.6
          ansible_user: kubeadm
        #  kubevip_interface: enp0s25
          
    worker:
      hosts:
        k3s-pi-1:
          ansible_host: 192.168.1.2
        k3s-pi-2:
          ansible_host: 192.168.1.3
          rook_partitions:
            - /dev/sda3
        k3s-pi-3:
          ansible_host: 192.168.1.4
          rook_partitions:
            - /dev/sda3
