---
kubernetes:
  children:
    master:
      hosts:
        k3s-pi-1:
          ansible_host: 192.168.1.2
    worker:
      hosts:
        k3s-pi-2:
          ansible_host: 192.168.1.3
        k3s-pi-3:
          ansible_host: 192.168.1.4
