# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:4x9tqR3OGmzLBvIlPz5fe8yh,iv:y0JmAP+MS1NYgEQx6TNuOG1zh4cl1wMrlr0txoYbFjY=,tag:X58WuxD452/JHX0+1UZM9Q==,type:str]
    SECRET_LOCAL_DOMAIN: ENC[AES256_GCM,data:jaDEozgGzFpR59i1/tr9kknJw5b42To=,iv:8IGoUf1KwDMnFT9vuQzFuY1D+6eHG0xA0f3+VbCqQTY=,tag:1WBRVJA7rzO30/4kqS0mmw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:HTth6V6T2NE8IHd0XNJCCEBVH21gDjHSS7+cNQ==,iv:EdvWytrnzP5udnn/8yOkjY399UUi/c1tzFegRs3e57Q=,tag:O6/z1VFTC916KTt3EOJNFw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15z2406qz970ed0p8ptd30pu5k9cl7ph6x6fvjvpaxvqc4pslnfms68ftet
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2b2QxNWdOU3Q3NEthOWNC
            aGxBU2JES3J1VmhoaFRQSzFoVVBpZlFlSGhzClNYOVBId3BVSytzVUZndEc3Z29s
            OUs4dkIzaUp4WjBBYmN3NzI3NE1zZUEKLS0tIDdXQ0RVSStMQTlMb3plN3pXWlBv
            cy9JbFVuV2ZrcTY3T3NXYmpkUnNaN2sKZCLsC58tX5W5dbfNc73RVroch34V0YrF
            /EYQKYCTLc97nzzRGQAOKQ+f0V0Otau3hgbUlXyczoIYECYiEJJ87A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-02T16:25:27Z"
    mac: ENC[AES256_GCM,data:6NOZ0U6pRtpA6ovJ5NBGRQIJrvY3RFWPtXWzuAFscm3hqhsvPbh+TS1KehXYu8KV8oa2WUAxLSWONBVbkGaOiK9zZR1CtdrytE75jjSA0nvWFzxWu98MQN8TVs44wyrTIzRu4diS9SrpidQkGXjhzuEHa6h+EYoNdAD/UGVxy2E=,iv:wC+KJIGZfoQjD5mvUyfjH2SJnoPPlJCscgJyCjE6fHw=,tag:6iKG6PVWzbG1R9f1dSaWJQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
