# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:PXgp1ds6ByHTThssJjJkUI1W,iv:B9hmyqiWwAOAeqbzclqJFLpK0DiUP3yYhyzXNgNpx9Y=,tag:vE4ZShoKHvPXKm4vL0GwvQ==,type:str]
    SECRET_LOCAL_DOMAIN: ENC[AES256_GCM,data:hZWLKlUVYOUbAVp3V0j4rpko9+eX2M8=,iv:5vaBbKt0Efc7o4GICE8878Fzhlxmq7kqSHMi9IiJfgo=,tag:VHIHvNee0ph9BMxtN0fRrg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:zl6PdGQalnsRA6+dFhppOCi+whV6Sq0Fr1Y1zA==,iv:FVGCX8vVcsKUKXrstCkBkvmCnkVFGvWMboJH0Qe+ZfA=,tag:qe2e3r6oKEzmqMVEuJ8gmA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15z2406qz970ed0p8ptd30pu5k9cl7ph6x6fvjvpaxvqc4pslnfms68ftet
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoSC9BZTZhc0NHRy9FanRF
            TVdSeUcxVjI1RUYwUVZDL0tHdDFqVWhoZDE0Ck42cXFrVVVXZlh4OW5UZWF1aDdP
            cENRWW1TVC9wUUJOZGpiYzJWcExVcTgKLS0tIGlBRHhzbGIxcGhsZjlYd0JkS3Iz
            VHNUTjRDMXgxcDJndzl6WTN5UlV4dVEKjHZhWYvxGsRdinKd+TrrnXWHcYVboOYa
            eQK/YeklPXb6XLkrAS5XlQWYal414wmUOBJmSsHL2jujNQsid1G3rg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-07T10:38:57Z"
    mac: ENC[AES256_GCM,data:AkAfjSdr8pWLfhyIFOKXSoDlg0qpcstP+qmEJJ8U8BrUL8gZFp+aAQm+TcC9aH218iRJ7f2aEy/GR0SpP++KmBZxmBZRqyFX1ED8g2TV3+2jqX7yBrfAtUtq30/TsKETS89tQrGHKgU0dILUeeO+6eUpN7ZmrQpExGBpY5mtRKI=,iv:veacHBtvZ8nl7UXzYiR1KxnVm00UNAlXGmbTQK4GOTY=,tag:1P8D0NJZbuiYhKwuRERH/w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
