# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:PXgp1ds6ByHTThssJjJkUI1W,iv:B9hmyqiWwAOAeqbzclqJFLpK0DiUP3yYhyzXNgNpx9Y=,tag:vE4ZShoKHvPXKm4vL0GwvQ==,type:str]
    SECRET_LOCAL_DOMAIN: ENC[AES256_GCM,data:hZWLKlUVYOUbAVp3V0j4rpko9+eX2M8=,iv:5vaBbKt0Efc7o4GICE8878Fzhlxmq7kqSHMi9IiJfgo=,tag:VHIHvNee0ph9BMxtN0fRrg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:zl6PdGQalnsRA6+dFhppOCi+whV6Sq0Fr1Y1zA==,iv:FVGCX8vVcsKUKXrstCkBkvmCnkVFGvWMboJH0Qe+ZfA=,tag:qe2e3r6oKEzmqMVEuJ8gmA==,type:str]
    SECRET_TELEGRAM_API_TOKEN: ENC[AES256_GCM,data:Ocua4xmdZ58R0lNs2gAiM+aOUsYdmSWcUNwlwzj4rVOgmWN09nV7dIxQKfwqXQ==,iv:HU3aupWL3wWnIArKbKFa/bBv43kuFXAbQ0QN5CwtXTE=,tag:VMn+hGphXFa09qYOnUlq1g==,type:str]
    SECRET_TELEGRAM_CHAT_ID: ENC[AES256_GCM,data:fJXO7w0rBwN/vg==,iv:hGrXxZ4c4xuaqL0VFzYtbvaUXHjXWx6hK89GP5rczcM=,tag:vSZNwaR9mI6jCFSxF3UpKg==,type:str]
    SECRET_GRAFANA_PASSWORD: ENC[AES256_GCM,data:2Wxxnldg8XakvfS2fYl+3JYBilQi/t/xKWLSKQ4ahuXKDesujRk0pQ==,iv:j0eg0VGHu26rmeQIAuMmOvHRqHR15Itf/qnO3nhv3HI=,tag:foSNICWw2loSvAJJVsDeew==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15z2406qz970ed0p8ptd30pu5k9cl7ph6x6fvjvpaxvqc4pslnfms68ftet
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoSC9BZTZhc0NHRy9FanRF
            TVdSeUcxVjI1RUYwUVZDL0tHdDFqVWhoZDE0Ck42cXFrVVVXZlh4OW5UZWF1aDdP
            cENRWW1TVC9wUUJOZGpiYzJWcExVcTgKLS0tIGlBRHhzbGIxcGhsZjlYd0JkS3Iz
            VHNUTjRDMXgxcDJndzl6WTN5UlV4dVEKjHZhWYvxGsRdinKd+TrrnXWHcYVboOYa
            eQK/YeklPXb6XLkrAS5XlQWYal414wmUOBJmSsHL2jujNQsid1G3rg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-30T12:46:35Z"
    mac: ENC[AES256_GCM,data:oQw7vJ6f1niNc0quKkdgBu9PDdyT/5G2uj+Vp+YwXSm6YepJW1IzHC1qaVrU/DCWJX0bud4Y93A+luhytxAPVA0R7rJMQe0Ys3vgyUjk0b4r2n4lPP/fbaS9Zp/mmWyYZ6bGa/CHDnZK0aY85JVE01LEkaAV1QsJIs/n6ClyHUw=,iv:b8HPmm+jcQ3KQer/2L5dKGzKCPRXwfvlf+tHLVQQLHg=,tag:qqf/kkbIKxMa87BodzJ+bw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
