---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: thanos-ceph-bucket
  namespace: monitoring
spec:
  
  generateBucketName: thanos
  storageClassName: rook-ceph-bucket
  # additionalConfig: [5]
  #   maxObjects: "1000"
  #   maxSize: "2G"
