---
kind: "Service"
apiVersion: "v1"
metadata:
  name: "portainer"
spec:
  ports:
    -
      name: "web"
      protocol: "TCP"
      port: 9000
      targetPort: 9000
      nodePort: 0
---
kind: "Endpoints"
apiVersion: "v1"
metadata:
  name: "portainer"
subsets:
  -
    addresses:
      -
        ip: "192.168.1.12"
    ports:
      -
        port: 9000
        name: "portainer"
