---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: k8s-nfs-backup-pv
  namespace: benji
spec:
  capacity:
    storage: 512Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: xbmc
    path: /data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k8s-nfs-backup-pvc
  namespace: benji
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
