# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: uptimerobot-heartbeat-url
    namespace: monitoring
stringData:
    UPTIMEROBOT_HEARTBEAT_URL: ENC[AES256_GCM,data:P7fYMeLhX7LMrRMWsb+98da/SA6VWDXWfnoNZu9apIHcMBPkEfeSSbl8SC2BbRgZ2P62K5PIt0h3c/YLHicBJzTIVMjERFs/NZJ/nCWMfceo3GSUwQ==,iv:zMFAV9sZT+sHOVLGqqvJkqatcJbFme7ADmc1lfkTYVE=,tag:hEGoIyueZbtsf65zHSl30w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15uzrw396e67z9wdzsxzdk7ka0g2gr3l460e0slaea563zll3hdfqwqxdta
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPT1daQTNHeFpjbXVnOHpY
            SGRlNzNTdThvUEd5UmtHbzlFMnZhcmx4OVFVCjN1U1l4TStBRm1ReFYvc2F0Wm0z
            YUlOM0c4eUdLQkJuVzE2MUJteUZ6bm8KLS0tIFdJL094bTFRUU5JSXorT3Vhc3Vm
            QXBaVW1yZTloeXdKU1JkcnJiT0s5VmsK6JInvkq7ILQPTiKedDZEa0rhpONTSFwc
            SS5sGjmN0fog7zjSa97iY4x1iuwV3Iwi0rQk39gj0PXKkXYkl/ILtQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-11-24T16:55:14Z"
    mac: ENC[AES256_GCM,data:7w0h55Opec1a3jLkrU1IfzHtdFfUY2uD7RhTuZWdWVHc6l2uXPsd9rrE8lT5TSlTUm76/8QZofnhef+XnUgE5gz9UGp5c4YuyLbuLgfM8YmsnLj0DA/WJwZoJjlYkJHiNlBOLjErBfsl9H0IKAwlifG5mwfrEX2slzhl/NWUPGo=,iv:g72d7vuf4U9fcfBLz8oFyCdZMn6zFijWDhKjCTn+Xvw=,tag:LDOjLzgHb0lB5hW0HQcIsA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
