---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pushgateway
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://prometheus-community.github.io/helm-charts
      chart: prometheus-pushgateway
      version: 1.20.1
      sourceRef:
        kind: HelmRepository
        name: prometheus-community-charts
        namespace: flux-system
      interval: 5m
  values:
    fullnameOverride: pushgateway
    ingress:
      enabled: true
      className: traefik
      path: /
      hosts:
        - "pushgateway.${SECRET_LOCAL_DOMAIN}"
      tls:
        - hosts:
            - "pushgateway.${SECRET_LOCAL_DOMAIN}"
    serviceMonitor:
      enabled: true
      namespace: monitoring
