# yamllint disable
# comm_config.yaml: |
#     communications:
#         discord:
#             enabled: true
#             notiftype: short
#             token:
#             botid:
#             channel:
apiVersion: v1
kind: Secret
metadata:
    name: botkube-communications
    namespace: monitoring
stringData:
    comm_config.yaml: ENC[AES256_GCM,data:pEa3+dXopwLmY8NIMKsiZrfWHMToEDRv7EnSEJXfRvhucGhEY0CGeGABx2AC2907NGOtMp8UBCe+iABd1i1DgroBH7qPzpms/c1J30Pwu5hVrURw/bW8bpngCiEorHaBbDWushBh4oUThSw/flJVWR+th/rfuQ5UywP1fo8L++qT0slyAC4mwbtqz4YuLzr6KrZstRA8TwmQzfd9dLcUr0JaGXCEhMcHDgm3IHcZqciEanmUivBlGJJ6jQbE0sHDMPhnLeXs3iGA7mjWUdEUC5MZ4hzzbXgJH9OWI2y6NqdQ1/A=,iv:wol3ZdqqHl687U9EXCgCqeYqZcBHobeD+ukNSWmk4uI=,tag:9uZ3oiTGE4rsM+hSXNvQwg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15uzrw396e67z9wdzsxzdk7ka0g2gr3l460e0slaea563zll3hdfqwqxdta
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnNzJNSndvK3lXMmNhZ3Za
            ZTU3SEJTVHA2TFdJc29TZ2hvZ0FqcHdZaGhZCm5iRlNQT29CdkhBcGJaYXdFdU5i
            Z0kvaTRxM1cyOXgxT3JRZnBUcGwySjgKLS0tIGtVckZmVEdXdUpuZUJYZTliaDln
            blluMGZwV0RQdDRCQzQwaVFZOUtzejAKqB3Tz21xIsKmb3EmLp4qQvcnOcDS0Ga0
            TGo3crwSofMpi0Z78kI33X0cUyH9vpRu4TlPVVUBKJAoMcJPClz2mw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-11-24T16:55:14Z"
    mac: ENC[AES256_GCM,data:mQNiK03NE/w/g4i9sif4sD+rM1tuJmkWr9tI00PZkZsBf8lLoxqWw1wWv1oL85AYebkhIsJ58PgooQSkfrU8HsG8sor5E/MRwab8ewni8xUR6Or3CLGljMb8/pNwMEvr2xhgYg0eLrokq3DAo8WDkuS/grnn430j4tDTOWk4hrE=,iv:jnJUubCVE1AUcXJGuKhJ/9ex5xRDXOJaR4aUpH55Jms=,tag:AsHUUeakQU2Ld9fY5zm2Xg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
